### ISSUE TITLE
Received two DMs after goal set cancelling, expected none

### ISSUE THREAD

**Issue by cdupuis** [atomist/sdm-core#177]
Issue moved from atomist/atomist-sdm#196

Created by @kipz at 2019-06-26T09:20:28Z:

I cancelled a goalset because I'd quickly corrected an issue and pushed it whilst the previous one was still building, and I got two DM's about a failure, but really it was cancelled.

At the very least, I think I should only get the one.

![Screenshot_20190626_101917](https://user-images.githubusercontent.com/1865026/60167865-db19d700-97fb-11e9-824c-b9ff653f5b1a.png)

**Comment by cdupuis** [comment]
@kipz, I looked at the logs and it seems you pressed `Restart build` instead of cancel. I have the incoming command request here and also no trace of a cancel request on the goal set itself.

**Comment by kipz** [comment]
@cdupuis there's no restart whilst it's running, right?

**Comment by cdupuis** [comment]
No there isn't. But your command request came in after the initial Build goal already failed.

**Comment by kipz** [comment]
I guess that as I was clicking cancel, it very quickly, before I could see it, switched to "restart", and I clicked that without noticing, and got two failed builds.
